### ISSUE TITLE
[pixels-common] check the S3 connection and reconnect if it is closed.

### ISSUE THREAD

**Issue by bianhq** [pixelsdb/pixels#328]
Sometimes we get errors like this:
```log
software.amazon.awssdk.crt.http.HttpException: The connection has closed or is closing.
	at software.amazon.awssdk.http.crt.internal.AwsCrtAsyncHttpStreamAdapter.onResponseComplete(AwsCrtAsyncHttpStreamAdapter.java:116) [pixels-lambda-deps.jar:?]
	at software.amazon.awssdk.crt.http.HttpStreamResponseHandlerNativeAdapter.onResponseComplete(HttpStreamResponseHandlerNativeAdapter.java:58) [pixels-lambda-deps.jar:?]
```

**Comment by bianhq** [comment]
Fixed in Issue #347.
