### ISSUE TITLE
[pixels-core] Reading Vulong past EOF occasionally appears when reading integer columns.

### ISSUE THREAD

**Issue by bianhq** [pixelsdb/pixels#51]
The following exceptions occasionally appears when executing `select * from test_105 order by QueryDate_ limit 10`.
```java
com.facebook.presto.spi.PrestoException: Reading Vulong past EOF
	at io.pixelsdb.pixels.presto.PixelsPageSource$PixelsBlockLoader.load(PixelsPageSource.java:286)
	at io.pixelsdb.pixels.presto.PixelsPageSource$PixelsBlockLoader.load(PixelsPageSource.java:252)
	at com.facebook.presto.spi.block.LazyBlock.assureLoaded(LazyBlock.java:255)
	at com.facebook.presto.spi.Page.assureLoaded(Page.java:241)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:265)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:278)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:659)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:272)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:975)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: Reading Vulong past EOF
	at io.pixelsdb.pixels.core.encoding.RunLenIntDecoder.readVulong(RunLenIntDecoder.java:491)
	at io.pixelsdb.pixels.core.encoding.RunLenIntDecoder.readVslong(RunLenIntDecoder.java:502)
	at io.pixelsdb.pixels.core.encoding.RunLenIntDecoder.readDeltaValues(RunLenIntDecoder.java:322)
	at io.pixelsdb.pixels.core.encoding.RunLenIntDecoder.readValues(RunLenIntDecoder.java:109)
	at io.pixelsdb.pixels.core.encoding.RunLenIntDecoder.next(RunLenIntDecoder.java:71)
	at io.pixelsdb.pixels.core.reader.IntegerColumnReader.read(IntegerColumnReader.java:114)
	at io.pixelsdb.pixels.core.reader.PixelsRecordReaderImpl.readBatch(PixelsRecordReaderImpl.java:652)
	at io.pixelsdb.pixels.presto.PixelsPageSource$PixelsBlockLoader.load(PixelsPageSource.java:282)
	... 15 more
```

```java
java.lang.ArrayIndexOutOfBoundsException: 0
	at io.pixelsdb.pixels.core.encoding.RunLenIntDecoder.readPatchedBaseValues(RunLenIntDecoder.java:246)
	at io.pixelsdb.pixels.core.encoding.RunLenIntDecoder.readValues(RunLenIntDecoder.java:106)
	at io.pixelsdb.pixels.core.encoding.RunLenIntDecoder.next(RunLenIntDecoder.java:71)
	at io.pixelsdb.pixels.core.reader.IntegerColumnReader.read(IntegerColumnReader.java:114)
	at io.pixelsdb.pixels.core.reader.PixelsRecordReaderImpl.readBatch(PixelsRecordReaderImpl.java:652)
	at io.pixelsdb.pixels.presto.PixelsPageSource$PixelsBlockLoader.load(PixelsPageSource.java:282)
	at io.pixelsdb.pixels.presto.PixelsPageSource$PixelsBlockLoader.load(PixelsPageSource.java:252)
	at com.facebook.presto.spi.block.LazyBlock.assureLoaded(LazyBlock.java:255)
	at com.facebook.presto.spi.Page.assureLoaded(Page.java:241)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:265)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:278)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:659)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:272)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:975)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by bianhq** [comment]
Some times the error could also be:
```java
java.lang.ArrayIndexOutOfBoundsException: 0
	at io.pixelsdb.pixels.core.encoding.RunLenIntDecoder.readPatchedBaseValues(RunLenIntDecoder.java:256)
	at io.pixelsdb.pixels.core.encoding.RunLenIntDecoder.readValues(RunLenIntDecoder.java:116)
	at io.pixelsdb.pixels.core.encoding.RunLenIntDecoder.next(RunLenIntDecoder.java:72)
	at io.pixelsdb.pixels.core.reader.IntegerColumnReader.read(IntegerColumnReader.java:140)
	at io.pixelsdb.pixels.core.reader.PixelsRecordReaderImpl.readBatch(PixelsRecordReaderImpl.java:656)
	at io.pixelsdb.pixels.presto.PixelsPageSource$PixelsBlockLoader.load(PixelsPageSource.java:282)
	at io.pixelsdb.pixels.presto.PixelsPageSource$PixelsBlockLoader.load(PixelsPageSource.java:252)
	at com.facebook.presto.spi.block.LazyBlock.assureLoaded(LazyBlock.java:255)
	at com.facebook.presto.spi.Page.assureLoaded(Page.java:241)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:265)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:278)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:659)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:272)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:975)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by bianhq** [comment]
This issue is much likely to be same issue #99.
No error for the above query after Issue #99 is resolved.
So we close this issue.
