### ISSUE TITLE
[pixels-daemon] failed to create view

### ISSUE THREAD

**Issue by bianhq** [pixelsdb/pixels#704]
Pixels-daemon reports the following error when creating view in Trino:
```java
java.sql.SQLException: Field 'VIEW_ID' doesn't have a default value
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at io.pixelsdb.pixels.daemon.metadata.dao.impl.RdbViewDao.insert(RdbViewDao.java:196) [pixels-daemon-0.2.0-SNAPSHOT-full.jar:?]
        at io.pixelsdb.pixels.daemon.metadata.MetadataServiceImpl.createView(MetadataServiceImpl.java:1526) [pixels-daemon-0.2.0-SNAPSHOT-full.jar:?]
        at io.pixelsdb.pixels.daemon.MetadataServiceGrpc$MethodHandlers.invoke(MetadataServiceGrpc.java:3416) [pixels-daemon-0.2.0-SNAPSHOT-full.jar:?]
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182) [pixels-daemon-0.2.0-SNAPSHOT-full.jar:?]
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:354) [pixels-daemon-0.2.0-SNAPSHOT-full.jar:?]
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:866) [pixels-daemon-0.2.0-SNAPSHOT-full.jar:?]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [pixels-daemon-0.2.0-SNAPSHOT-full.jar:?]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) [pixels-daemon-0.2.0-SNAPSHOT-full.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
```

**Comment by bianhq** [comment]
Done.
